name: Docker Build and Push

on:
  push:
    branches: [main]
  # Optionally enable manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gisual-interview-api:latest,${{ secrets.DOCKER_USERNAME }}/gisual-interview-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
